# This is a basic workflow to help you get started with Actions

name: nginx config validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master
    paths:
      - 'env-dev/sites/**'
  pull_request:
    branches:
      - master
    paths:
      - 'env-dev/sites/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validates:
    # The type of runner that the job will run on
    runs-on: wsl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          sparse-checkout: env-dev/sites

      # Backups previous config files
      - name: Backup nginx config file
        run: sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

      # Replaces config file with repos file
      - name: Replace nginx file
        run: sudo cp ./env-dev/nginx.conf /etc/nginx/nginx.conf

      # Runs a single command using the runners shell
      - name: Copy sites config
        run: sudo cp -R ./env-dev/sites/* /etc/nginx/sites-enabled/

      # Validates nginx config
      - name: Validate nginx config
        run: /usr/local/nginx/sbin/nginx -t
